In [26]:
import numpy as np
from paramiko import SSHClient
from UAV import *
import random
from sklearn.manifold import MDS

Definition of the Distance Matrix

In [27]:
n_robots = int(input("number of robots: "))
platoon = []

# initialization of n robots
for i in range(n_robots):
    i_robot = Robot("op_" + str(i),random.uniform(0, 10.0),random.uniform(0, 10.0),0)
    platoon.append(i_robot)

DM = d_matrix(platoon)
print(DM)

[[0.         4.87648178 2.13377046]
 [4.87648178 0.         3.21041103]
 [2.13377046 3.21041103 0.        ]]


Identity matrix

In [28]:
I   = np.eye(n_robots)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Definition of the e vector and the H matrix

In [29]:
e   = np.array([1/n_robots for i in range(n_robots)])
etr = np.array([[1/n_robots] for i in range(n_robots)])

H = I - e*etr
print(H)

[[ 0.88888889 -0.11111111 -0.11111111]
 [-0.11111111  0.88888889 -0.11111111]
 [-0.11111111 -0.11111111  0.88888889]]


Eigendecomposition of the matrix -1/2*H*D*H

In [30]:
print(-1/2*H*DM*H,'\n')

#Eigenvalues ev, eigenvectors EV
ev,EV = np.linalg.eig(-1/2*H*DM*H)

#Lambda is the diagonal matrix whose elements are the eigenvalues
LAMBDA = np.eye(n_robots)*ev

#U is the matrix whose columns are the eigenvectors
U      = np.transpose(EV)
print(LAMBDA,'\n\n',U)

Sstar  = np.sqrt(LAMBDA).transpose(U)

print(Sstar)

[[-0.         -0.03010174 -0.01317142]
 [-0.03010174 -0.         -0.01981735]
 [-0.01317142 -0.01981735 -0.        ]] 

[[-0.04288116  0.          0.        ]
 [-0.          0.0310963   0.        ]
 [-0.          0.          0.01178487]] 

 [[ 0.59797867  0.64170997  0.48023934]
 [ 0.63400754 -0.74527181  0.20640825]
 [-0.49036308 -0.18104763  0.8525056 ]]


/tmp/ipykernel_13468/2287130934.py:13: RuntimeWarning: invalid value encountered in sqrt
  Sstar  = np.sqrt(LAMBDA).transpose(U)


TypeError: only integer scalar arrays can be converted to a scalar index

Scikit learn MDS approach

In [33]:
n_components = 2                                   # p, reduced dimensionality space
embedding = MDS(n_components=2,n_init = 20,max_iter = 1000,random_state = 73073,dissimilarity='precomputed') # instantiate and set the hyperparameter
MDS_transformed = embedding.fit_transform(DM)
MDS_transformed.shape
print(MDS_transformed)

[[-2.21109124  0.39919293]
 [ 2.61359693  0.41537717]
 [-0.40250569 -0.8145701 ]]
