In [4]:
import numpy as np
from paramiko import SSHClient
from UAV import *
import random

Definition of the Distance Matrix

In [10]:
n_robots = int(input("number of robots: "))
platoon = []

# initialization of n robots
for i in range(n_robots):
    i_robot = Robot("op_" + str(i),random.uniform(0, 10.0),random.uniform(0, 10.0),0)
    platoon.append(i_robot)

DM = d_matrix(platoon)
print(DM)

[[ 0.          7.69628883  7.97206749  6.36926142  7.70556769]
 [ 7.69628883  0.          4.69052965  6.45134368  4.26694108]
 [ 7.97206749  4.69052965  0.         10.06237505  8.65014365]
 [ 6.36926142  6.45134368 10.06237505  0.          2.92790526]
 [ 7.70556769  4.26694108  8.65014365  2.92790526  0.        ]]


Identity matrix

In [11]:
I   = np.eye(n_robots)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Definition of the e vector and the H matrix

In [13]:
e   = np.array([1/n_robots for i in range(n_robots)])
etr = np.array([[1/n_robots] for i in range(n_robots)])

H = I - e*etr
print(H)

[[ 0.96 -0.04 -0.04 -0.04 -0.04]
 [-0.04  0.96 -0.04 -0.04 -0.04]
 [-0.04 -0.04  0.96 -0.04 -0.04]
 [-0.04 -0.04 -0.04  0.96 -0.04]
 [-0.04 -0.04 -0.04 -0.04  0.96]]


Eigendecomposition of the matrix -1/2*H*D*H

In [16]:
#Eigenvalues ev, eigenvectors EV
ev,EV = np.linalg.eig(-1/2*H*DM*H)

#Lambda is the diagonal matrix whose elements are the eigenvalues
LAMBDA = np.eye(n_robots)*ev

#U is the matrix whose columns are the eigenvectors
U      = np.transpose(EV)
print(LAMBDA,'\n\n',U)

Sstar  = np.sqrt(LAMBDA).transpose(U)

print(Sstar)

[[-0.02162205  0.          0.          0.          0.        ]
 [-0.          0.0017754   0.          0.          0.        ]
 [-0.          0.          0.00288256  0.          0.        ]
 [-0.          0.          0.          0.00719356  0.        ]
 [-0.          0.          0.          0.          0.00977053]] 


 [[-0.48074761 -0.39370428 -0.50430094 -0.4392394  -0.40820091]
 [-0.11660969  0.4000139  -0.09337679  0.5460936  -0.72073131]
 [-0.32695977 -0.67219106  0.49564872  0.43923576 -0.0515828 ]
 [-0.80503235  0.44617753  0.09834417  0.01697905  0.37800616]
 [-0.01743927  0.18458228  0.69398999 -0.56181331 -0.41032786]]


/tmp/ipykernel_13468/3205072644.py:11: RuntimeWarning: invalid value encountered in sqrt
  Sstar  = np.sqrt(LAMBDA).transpose(U)


TypeError: only integer scalar arrays can be converted to a scalar index